name: tutor_app
description: "A new Flutter project."
version: 0.2.0
publish_to: 'none'

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  bloc_test: ^9.1.7
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.1
  firebase_auth: ^5.2.1
  firebase_storage: ^12.3.6
  image_picker: ^1.1.2


  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  go_router: ^14.2.8
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.4
  equatable: ^2.0.5
  badges: ^3.1.2
  meta: ^1.12.0
  rxdart: ^0.28.0
  flutter_webrtc: ^0.12.1
  webrtc_repository:
    path: packages/repository/webrtc_repository
  internet_connection:
    path: packages/wrapper/connection
  authentication_repository:
    path: packages/repository/authentication_repository
  cloud_storage_repository:
    path: packages/repository/cloud_storage_repository
  storage:
    path: packages/models/storage
  
  signaling:
    path: packages/services/signaling
  flutter_background: ^1.3.0+1
  llm:
    path: packages/services/llm
  llm_model:
    path: packages/models/llm_model
  chat_bubbles: ^1.6.0
  group:
    path: packages/models/group
  speech_to_text: ^7.0.0
  flutter_animate: ^4.5.2
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  


flutter:
  uses-material-design: true

  assets:
    -  assets/icons/google_icon.png
    -  assets/icons/apple.png
    -  assets/icons/github.png

    -  assets/icons/tutor.png
    -  assets/background/nuu.jpg