name: webrtc
description: 
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  meta: ^1.12.0
  equatable: ^2.0.5

  
  
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
