name: signaling
description: 
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:

  flutter_webrtc: ^0.12.1+hotfix.1
  flutter:
    sdk: flutter
  cloud_firestore: ^5.4.2
  storage:
    path: ../../models/storage

  firebase_core: ^3.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
