name: cloud_storage_repository
description: 
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:

 
  cloud_storage:
    path: ../../wrapper/cloud_storage
  storage:
    path: ../../models/storage

  meta: ^1.12.0
  cloud_firestore: ^5.4.1
  flutter:
    sdk: flutter
 

dev_dependencies:

  flutter_test:
    sdk: flutter
