name: cloud_storage
description: without test
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:

  cloud_firestore: ^5.4.1
  equatable: ^2.0.5
  firebase_core: ^3.4.1
  meta: ^1.12.0
  flutter:
    sdk: flutter
  storage:
    path: ../../models/storage


dev_dependencies:
  flutter_test:
    sdk: flutter
