name: form_inputs
description: 
version: 0.0.1
publish_to: none
environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:

  formz: ^0.7.0

  flutter:
    sdk: flutter
    
dev_dependencies:

  flutter_test:
    sdk: flutter

