name: authentication_repository
description: 
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:

  storage:
    path: ../../models/storage
  auth:
    path: ../../wrapper/auth

  
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  meta: ^1.12.0

dev_dependencies:

  flutter_test:
    sdk: flutter
